# Generated by Django 4.2.2 on 2023-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='unknown', max_length=250)),
                ('book_author', models.CharField(default='True', max_length=200)),
                ('no_of_pages', models.IntegerField()),
                ('publish_date', models.DateField(default='null')),
                ('email_id', models.CharField(default='unknown', max_length=150)),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
