# Generated by Django 4.2.2 on 2023-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_details_email_id_alter_details_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email_id',
            field=models.EmailField(default='unknown', max_length=254),
        ),
    ]
