# Generated by Django 4.2.2 on 2023-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_details_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
